import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
const moduleFile = process.env.ASTRO_UI_MODULE_DIR ? pathToFileURL(resolve(process.env.ASTRO_UI_MODULE_DIR,'data.mjs')).href : './ui/data.mjs';
const {getAstroViews,preferredChart,getDomainFacts,resolveLocalAdvanced,endpoint1,endpoint2} = await import(moduleFile);
let checks=0;
const load=async name => JSON.parse(await readFile(new URL(`../${name}-result.json`,import.meta.url),'utf8'));
const natal=await load('natal');const n=getAstroViews(natal)[0];assert.equal(n.placements.length,10);assert.equal(n.houses.length,12);assert.equal(n.angles.length,4);assert.equal(n.aspects.length,natal.data.aspects.length);checks++;
const domains=await load('natal-domains');const d=getAstroViews(domains)[0];assert.equal(d.domains.length,10);assert.equal(d.aspects.length,domains.data.context.aspects.length);assert.ok(d.aspects.some(a=>a.point1==='H1'||a.point2==='H1'));checks++;
const career=getDomainFacts(d,'career','profession');assert.deepEqual(career.aspects.map(a=>a.index),domains.data.domains.career.report.aspects.filter(a=>domains.data.domains.career.report.sections[0].aspectIndexes.includes(a.index)).map(a=>a.index));checks++;
const couple=await load('couple');const c=getAstroViews(couple);assert.deepEqual(c.map(v=>v.key),['synastry','A','B']);assert.equal(c[0].placements.length,20);assert.equal(c[0].houses.length,24);assert.equal(c[0].domains.length,6);assert.ok(c[0].aspects.every(a=>endpoint1(a).startsWith('A:')&&endpoint2(a).startsWith('B:')));checks++;
const report=getDomainFacts(c[0],'attraction','chemistry');assert.ok(report.houses.every(h=>h.chartId==='A'||h.chartId==='B'));const chains=resolveLocalAdvanced(couple,c[0],report.report,'dispositorChains');assert.equal(chains.length,report.report.dispositorChainRefs.length);assert.ok(chains.some(x=>x.chartId==='A')&&chains.some(x=>x.chartId==='B'));checks++;
const composite=await load('composite');const cv=getAstroViews(composite);assert.equal(preferredChart(composite,cv),'C');const cp=cv.find(v=>v.key==='C');assert.ok(cp.placements.every(p=>p.speed===null&&p.isRetrograde===null));assert.ok(cp.aspects.every(a=>a.applying===null));checks++;
const forecast=await load('forecast-day');const fv=getAstroViews(forecast);assert.deepEqual(fv.map(v=>v.key),['transits','N','T']);assert.equal(fv[0].placements.length,20);assert.equal(fv[0].houses.length,12);assert.equal(fv[2].houses.length,0);assert.ok(fv[0].aspects.every(a=>endpoint1(a).startsWith('T:')&&endpoint2(a).startsWith('N:')));checks++;
const fd=getDomainFacts(fv[0],'career','profession');assert.deepEqual(fd.eventIds,forecast.data.domains.career.sections[0].eventIds);assert.ok(fd.aspects.every(a=>forecast.data.domains.career.sections[0].snapshotAspectIndexes.includes(a.index)));checks++;
const events=await load('events-year');const sky=getAstroViews(events)[0];assert.equal(sky.placements.length,10);assert.equal(sky.houses.length,0);assert.equal(sky.angles.length,0);checks++;
const points=await load('query-points');const pv=getAstroViews(points)[0];assert.deepEqual(pv.points,points.data.points);assert.ok(pv.placements.length<=10);checks++;
assert.deepEqual(getAstroViews({data:null,errors:[{code:'INVALID_INPUT',message:'bad'}]}),[]);checks++;
console.log(`Astro UI payload adapters: ${checks} checks PASS${process.env.ASTRO_UI_MODULE_DIR ? ' (installed package)' : ''}`);
